Add changes
turion/essence-of-live-coding pull request #90
Opened 2022-01-09 13:54 UTC by miguel-negrao

2022-01-09 14:18 UTC, miguel-negrao commented
I've placed changes next to hold as I think it as has a relationship to hold, since the following holds:

```Haskell
inputs ===  fst (runIdentity $ steps (changes >>> hold (head inputs)) inputs
```

So `changes >>> hold a` is similar to identity.

2022-01-09 16:44 UTC, turion commented
> I've placed changes next to hold as I think it as has a relationship to hold, since the following holds:
> 
> ```haskell
> inputs ===  fst (runIdentity $ steps (changes >>> hold (head inputs)) inputs
> ```
> 
> So `changes >>> hold a` is similar to identity.

Cool, if this holds, could you add a test?

2022-01-09 17:35 UTC, miguel-negrao commented
> Cool, if this holds, could you add a test?

The test for that property was already in the PR, it's in  essence-of-live-coding/test/Cell/Util.hs . I've added two more tests also.

2022-01-09 17:47 UTC, miguel-negrao commented
The property can also be stated as `delay a >>> changes >>> hold a == delay a`

2022-01-09 17:55 UTC, miguel-negrao commented
Ok, changed the test and haddock to `delay a >>> changes >>> hold a == delay a

2022-01-11 20:46 UTC, turion commented on essence-of-live-coding/src/LiveCoding/Cell/Util.hs
> +-- | Outputs @Just a@ whenever the the value a changes and Nothing otherwise.
```suggestion
-- | Outputs @'Just' a@ whenever the the value a changes and 'Nothing' otherwise.
```

2022-01-11 20:47 UTC, turion requested changes
Awesome! Two small haddock fixes.

2022-01-11 20:47 UTC, turion commented on essence-of-live-coding/src/LiveCoding/Cell/Util.hs
> +--  The first output is always Nothing. The following holds:
```suggestion
--  The first output is always 'Nothing'. The following holds:
```

2022-01-11 20:49 UTC, turion commented on essence-of-live-coding/src/LiveCoding/Cell/Util.hs
> +      if a /= aLast' then Just a else Nothing
You could also use `guard`, not sure whether that's better.

2022-01-12 10:47 UTC, miguel-negrao commented
Incorporated your suggestions, thanks for the review ! :)

2022-01-14 14:16 UTC, turion commented
Let's merge https://github.com/turion/essence-of-live-coding/pull/91/ first though, so we can test the changes on the new CI :sparkles:

2022-01-19 14:46 UTC, turion commented
Ok, can you rebase, then the CI will run thanks to your previous PR :tada:

2022-01-19 15:24 UTC, turion approved these changes

2022-01-22 16:48 UTC, miguel-negrao commented
I think this is ok to merge, right ?

2022-02-07 14:26 UTC, turion commented
Yes, I lost track, sorry.

2022-02-07 14:26 UTC, merged